In [14]:
import pandas as pd

tabela = pd.read_csv("clientes_banco.csv")
display(tabela)

#para remober as linhas com valores nulos, podemos usar o método .dropna() do pandas.
tabela.dropna()

,ID_CLIENTE,NOME,IDADE,CIDADE,SALDO,CATEGORIA,STATUS
0,101,Ana Silva,28,São Paulo,14500.50,Bronze,Ativo
1,102,Carlos Oliveira,45,Rio de Janeiro,89000.00,Gold,Ativo
2,103,Mariana Costa,34,Belo Horizonte,2300.00,Bronze,Inativo
3,104,Fernando Souza,52,Curitiba,150000.75,Platinum,Ativo
4,105,Juliana Lima,29,São Paulo,NaN,Bronze,Ativo
5,106,Lucas Pereira,61,Porto Alegre,42000.00,Silver,Ativo
6,107,Beatriz Rocha,22,Rio de Janeiro,850.20,Bronze,Inativo
7,108,Roberto Alves,39,São Paulo,95000.00,Gold,Ativo
8,109,Camila Martins,31,Curitiba,3100.00,Bronze,Ativo
9,110,Gustavo Ribeiro,48,Belo Horizonte,210000.00,Platinum,Ativo

,ID_CLIENTE,NOME,IDADE,CIDADE,SALDO,CATEGORIA,STATUS
0,101,Ana Silva,28,São Paulo,14500.50,Bronze,Ativo
1,102,Carlos Oliveira,45,Rio de Janeiro,89000.00,Gold,Ativo
2,103,Mariana Costa,34,Belo Horizonte,2300.00,Bronze,Inativo
3,104,Fernando Souza,52,Curitiba,150000.75,Platinum,Ativo
5,106,Lucas Pereira,61,Porto Alegre,42000.00,Silver,Ativo
6,107,Beatriz Rocha,22,Rio de Janeiro,850.20,Bronze,Inativo
7,108,Roberto Alves,39,São Paulo,95000.00,Gold,Ativo
8,109,Camila Martins,31,Curitiba,3100.00,Bronze,Ativo
9,110,Gustavo Ribeiro,48,Belo Horizonte,210000.00,Platinum,Ativo